### PR TITLE
fix: Do not allow swipe back on iOS modals

### LINKED ISSUE #871: iOS - When the screen is presented modally, swipe to back should not be possible
[video](https://trello-attachments.s3.amazonaws.com/5a742fedd88b9dc00a44bcc1/5b47424b9afae4ac2f985c39/78c18162cf725caccb5de36ca8d39262/ScreenRecording_07-12-2018_13-58-47.MP4)

### PR DESCRIPTION
**Pull request by ferrannp**
Fixes #871.

- [x] Fix withNativeNavigation for modals
- [x] Write unit test for the whole withNativeNavigation

### CODE REVIEW

File: packages/shared/src/WithNativeNavigation.js [hunk 1]
```diff
@@ -17,27 +19,41 @@ function withNativeNavigation<Props: {}>(
...
-        GestureController.disableGestures(moduleName);
-        this.currentIndex = currentState.index;
+      // Native gesture should only be enabled in the very first screen
+      // Also, there should not be modal (like first screen + modal)
+      const isDisabled =
+        currentState.routes.length > 1 ||
+        currentState.routes[0].routes.length > 1;
+
+      if (!isDisabled) {
+        if (this.lastCall !== 'enabled') {
```
Comment (tbergq) [inline packages/shared/src/WithNativeNavigation.js]: I don't like these nested ifs, can we get this in the same condition, or something like

```
if (disabled) callThisMEthod()
else callAnotherMethod()
```

File: packages/shared/src/WithNativeNavigation.js [hunk 2]
```diff
@@ -4,7 +4,9 @@ import * as React from 'react';
 import { GestureController } from '@kiwicom/mobile-shared';
 
 type NavigationState = {|
-  index: number,
+  routes: Array<{
+    routes: Array<mixed>,
+  }>,
```
Comment (tbergq) [inline packages/shared/src/WithNativeNavigation.js]: $ReadOnlyArray and exact types if possible please

File: packages/shared/src/__tests__/WithNativeNavigation.test.js [hunk 3]
```diff
@@ -0,0 +1,116 @@
+/* @flow */
```
Comment (tbergq) [inline packages/shared/src/__tests__/WithNativeNavigation.test.js]: This triggered my OCD, can this be `// @flow`

File: packages/shared/src/__tests__/WithNativeNavigation.test.js [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+import renderer from 'react-test-renderer';
+import { GestureController } from '@kiwicom/mobile-shared';
+
+import WithNativeNavigation from '../WithNativeNavigation';
+
+describe('WithNativeNavigation', () => {
+  const WrappedComponent = () => <View />;
+  const TestKey = 'test-key';
+  const getComponent = () => {
+    // $FlowFixMe injected props problem
```
Comment (tbergq) [inline packages/shared/src/__tests__/WithNativeNavigation.test.js]: can you please `$FlowExpectedError:` instead, and I don't understand the text. What is the problem with the injected prop?

File: packages/shared/src/WithNativeNavigation.js [hunk 5]
```diff
@@ -17,27 +19,39 @@ function withNativeNavigation<Props: {}>(
...
+      if (!isDisabled && this.lastCall !== 'enabled') {
         GestureController.enableGestures(moduleName);
-        this.currentIndex = 0;
-      } else if (currentState.index > 0) {
-        GestureController.disableGestures(moduleName);
-        this.currentIndex = currentState.index;
+        this.lastCall = 'enabled';
+        this.isEnabled = true;
+      } else {
+        if (this.lastCall !== 'disabled') {
```
Comment (tbergq) [inline packages/shared/src/WithNativeNavigation.js]: could you also fix this?
